Use artifacts to avoid hide failures from previous builds

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -9,18 +9,44 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Download previous failed files
+        uses: actions/download-artifact@v4
+        with:
+          name: failing-changed-files-for-lint
+          path: ./
+          if-no-files-found: ignore
       - name: Determine lint scope
         id: lint-scope
         run: |
           ./scripts/lint/determine-lint-scope.sh ${{ github.event.before }} ${{ github.event.after }} || echo "lints=" >> $GITHUB_OUTPUT
       - uses: docker/setup-buildx-action@v2
       - name: Run linters
+        id: run-linters
         run: |
           if [[ -n "${{ steps.lint-scope.outputs.lints }}" ]]; then
             make lint LINTS="${{ steps.lint-scope.outputs.lints }}"
           else
             make lint
           fi
+      - name: Save current changed files
+        run: |
+          git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} > current-changed-files.txt 2>/dev/null || echo "" > current-changed-files.txt
+      - name: Upload failed files
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: failing-changed-files-for-lint
+          path: current-changed-files.txt
+          retention-days: 7
+      - name: Upload success (empty file)
+        if: success()
+        run: |
+          echo "" > empty-failed-files.txt
+        uses: actions/upload-artifact@v4
+        with:
+          name: failing-changed-files-for-lint
+          path: empty-failed-files.txt
+          retention-days: 7
       - name: Check if wrong files have a error description
         run: make check-wrongs
       - name: Check if tags are correct
